/* Quiz — Banco de perguntas por tema (mín. 20 por tema) */

const QUIZ_DATA = {
  'Ciência': [
    { q: 'Qual é o símbolo químico da água?', options: ['H2O', 'CO2', 'NaCl', 'O2'], answer: 0 },
    { q: 'Quantos planetas tem o sistema solar?', options: ['7', '8', '9', '10'], answer: 1 },
    { q: 'Qual é o maior órgão do corpo humano?', options: ['Fígado', 'Cérebro', 'Pele', 'Coração'], answer: 2 },
    { q: 'Qual gás as plantas absorvem na fotossíntese?', options: ['Oxigénio', 'Azoto', 'Dióxido de carbono', 'Hidrogénio'], answer: 2 },
    { q: 'Qual é a velocidade da luz (aprox.)?', options: ['300 km/s', '300 000 km/s', '30 000 km/s', '3 000 000 km/s'], answer: 1 },
    { q: 'O que mede o termómetro?', options: ['Pressão', 'Temperatura', 'Humidade', 'Velocidade'], answer: 1 },
    { q: 'Qual é o elemento químico mais abundante no universo?', options: ['Oxigénio', 'Hélio', 'Hidrogénio', 'Carbono'], answer: 2 },
    { q: 'Quantos ossos tem o corpo humano adulto?', options: ['206', '208', '196', '300'], answer: 0 },
    { q: 'Qual planeta é conhecido como o "planeta vermelho"?', options: ['Vénus', 'Júpiter', 'Marte', 'Saturno'], answer: 2 },
    { q: 'O que é a mitose?', options: ['Divisão celular', 'Reação química', 'Tipo de rocha', 'Doença'], answer: 0 },
    { q: 'Qual é a fórmula do sal de cozinha?', options: ['KCl', 'NaCl', 'CaCl2', 'NaOH'], answer: 1 },
    { q: 'Que tipo de animal é a baleia?', options: ['Peixe', 'Réptil', 'Mamífero', 'Anfíbio'], answer: 2 },
    { q: 'Qual é o metal mais condutor de eletricidade?', options: ['Ouro', 'Cobre', 'Prata', 'Alumínio'], answer: 2 },
    { q: 'O ADN tem forma de…?', options: ['Hélice simples', 'Dupla hélice', 'Tripla hélice', 'Espiral plana'], answer: 1 },
    { q: 'Que unidade mede a força?', options: ['Joule', 'Watt', 'Newton', 'Pascal'], answer: 2 },
    { q: 'Qual é a estrela mais próxima da Terra?', options: ['Sirius', 'Alpha Centauri', 'Sol', 'Polaris'], answer: 2 },
    { q: 'Qual parte da célula contém o ADN?', options: ['Ribossoma', 'Mitocôndria', 'Núcleo', 'Membrana'], answer: 2 },
    { q: 'Quanto tempo demora a Terra a orbitar o Sol?', options: ['365 dias', '30 dias', '24 horas', '12 meses lunares'], answer: 0 },
    { q: 'Qual é o estado da matéria do gelo?', options: ['Líquido', 'Gasoso', 'Sólido', 'Plasma'], answer: 2 },
    { q: 'O que causa as marés?', options: ['Vento', 'Rotação da Terra', 'Gravidade da Lua', 'Correntes oceânicas'], answer: 2 },
    { q: 'Que gás respiramos para viver?', options: ['Azoto', 'Dióxido de carbono', 'Hélio', 'Oxigénio'], answer: 3 },
  ],
  'Geografia': [
    { q: 'Qual é a capital de Portugal?', options: ['Porto', 'Lisboa', 'Coimbra', 'Faro'], answer: 1 },
    { q: 'Qual é o rio mais longo do mundo?', options: ['Amazonas', 'Nilo', 'Mississípi', 'Yangtze'], answer: 1 },
    { q: 'Em que continente fica o Egito?', options: ['Ásia', 'Europa', 'África', 'América'], answer: 2 },
    { q: 'Qual é o maior oceano?', options: ['Atlântico', 'Índico', 'Pacífico', 'Ártico'], answer: 2 },
    { q: 'Qual país tem mais população?', options: ['EUA', 'Índia', 'China', 'Brasil'], answer: 1 },
    { q: 'Qual é a montanha mais alta do mundo?', options: ['K2', 'Monte Branco', 'Evereste', 'Kilimanjaro'], answer: 2 },
    { q: 'Quantos continentes existem?', options: ['5', '6', '7', '8'], answer: 2 },
    { q: 'Qual é o menor país do mundo?', options: ['Mónaco', 'Vaticano', 'San Marino', 'Liechtenstein'], answer: 1 },
    { q: 'Qual é a capital de França?', options: ['Lyon', 'Marselha', 'Paris', 'Nice'], answer: 2 },
    { q: 'Qual deserto é o maior do mundo?', options: ['Gobi', 'Kalahari', 'Antártida', 'Sara'], answer: 2 },
    { q: 'Que país tem forma de bota?', options: ['Grécia', 'Espanha', 'Itália', 'Croácia'], answer: 2 },
    { q: 'Qual é a ilha mais populosa do mundo?', options: ['Bornéu', 'Java', 'Grã-Bretanha', 'Honshu'], answer: 1 },
    { q: 'Onde fica Machu Picchu?', options: ['México', 'Colômbia', 'Peru', 'Bolívia'], answer: 2 },
    { q: 'Qual é a capital do Brasil?', options: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'], answer: 2 },
    { q: 'Em que continente fica a Austrália?', options: ['Ásia', 'Oceânia', 'América', 'África'], answer: 1 },
    { q: 'Qual é o país mais extenso do mundo?', options: ['Canadá', 'China', 'EUA', 'Rússia'], answer: 3 },
    { q: 'Que cordilheira separa Europa da Ásia?', options: ['Alpes', 'Andes', 'Urais', 'Himalaias'], answer: 2 },
    { q: 'Qual mar banha o sul de Portugal?', options: ['Mar do Norte', 'Mar Mediterrâneo', 'Oceano Atlântico', 'Mar Negro'], answer: 2 },
    { q: 'Qual é a capital de Espanha?', options: ['Barcelona', 'Sevilha', 'Madrid', 'Valência'], answer: 2 },
    { q: 'Que país é conhecido como "terra do sol nascente"?', options: ['China', 'Coreia do Sul', 'Tailândia', 'Japão'], answer: 3 },
    { q: 'Qual lago é o maior de África?', options: ['Lago Malawi', 'Lago Vitória', 'Lago Tanganica', 'Lago Chade'], answer: 1 },
  ],
  'História': [
    { q: 'Em que ano começou a Primeira Guerra Mundial?', options: ['1912', '1914', '1916', '1918'], answer: 1 },
    { q: 'Quem descobriu o caminho marítimo para a Índia?', options: ['Colombo', 'Magalhães', 'Vasco da Gama', 'Bartolomeu Dias'], answer: 2 },
    { q: 'Em que ano caiu o Muro de Berlim?', options: ['1987', '1989', '1991', '1985'], answer: 1 },
    { q: 'Qual civilização construiu as pirâmides de Gizé?', options: ['Romana', 'Grega', 'Egípcia', 'Persa'], answer: 2 },
    { q: 'Quem foi o primeiro homem na Lua?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'], answer: 2 },
    { q: 'Em que século ocorreu o Renascimento?', options: ['XII-XIII', 'XIV-XVI', 'XVII-XVIII', 'X-XI'], answer: 1 },
    { q: 'Qual revolução começou em 1789?', options: ['Americana', 'Industrial', 'Francesa', 'Russa'], answer: 2 },
    { q: 'Quem pintou a Mona Lisa?', options: ['Michelangelo', 'Rafael', 'Leonardo da Vinci', 'Botticelli'], answer: 2 },
    { q: 'Em que ano terminou a Segunda Guerra Mundial?', options: ['1943', '1944', '1945', '1946'], answer: 2 },
    { q: 'Qual país foi o primeiro a abolir a escravatura?', options: ['França', 'Portugal', 'Dinamarca', 'Reino Unido'], answer: 2 },
    { q: 'Quem escreveu "Os Lusíadas"?', options: ['Fernando Pessoa', 'Gil Vicente', 'Luís de Camões', 'Eça de Queirós'], answer: 2 },
    { q: 'Em que ano foi proclamada a República em Portugal?', options: ['1908', '1910', '1912', '1900'], answer: 1 },
    { q: 'Qual império dominou o Mediterrâneo na Antiguidade?', options: ['Grego', 'Romano', 'Persa', 'Cartaginês'], answer: 1 },
    { q: 'Quem liderou a Índia na independência pacífica?', options: ['Nehru', 'Gandhi', 'Bose', 'Patel'], answer: 1 },
    { q: 'Em que ano Cristóvão Colombo chegou à América?', options: ['1490', '1492', '1494', '1500'], answer: 1 },
    { q: 'Qual era a capital do Império Bizantino?', options: ['Roma', 'Atenas', 'Constantinopla', 'Alexandria'], answer: 2 },
    { q: 'Quem inventou a imprensa de tipos móveis?', options: ['Da Vinci', 'Gutenberg', 'Galileu', 'Newton'], answer: 1 },
    { q: 'O 25 de Abril em Portugal é que revolução?', options: ['Revolução Liberal', 'Revolução dos Cravos', 'Revolução Industrial', 'Revolução Republicana'], answer: 1 },
    { q: 'Qual conflito durou de 1337 a 1453?', options: ['Guerra dos 30 Anos', 'Guerras Púnicas', 'Guerra dos 100 Anos', 'Guerra das Rosas'], answer: 2 },
    { q: 'Em que ano o Homem pisou a Lua pela primeira vez?', options: ['1965', '1967', '1969', '1971'], answer: 2 },
    { q: 'Quem foi o primeiro rei de Portugal?', options: ['D. Sancho I', 'D. Afonso Henriques', 'D. Dinis', 'D. João I'], answer: 1 },
  ],
  'Tecnologia': [
    { q: 'Que linguagem é usada para estilizar páginas web?', options: ['HTML', 'JavaScript', 'CSS', 'Python'], answer: 2 },
    { q: 'O que significa "HTML"?', options: ['HyperText Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'HyperText Machine Language'], answer: 0 },
    { q: 'Quem fundou a Microsoft?', options: ['Steve Jobs', 'Bill Gates', 'Elon Musk', 'Mark Zuckerberg'], answer: 1 },
    { q: 'O que é um "bug" em programação?', options: ['Uma funcionalidade', 'Um erro', 'Um ficheiro', 'Uma variável'], answer: 1 },
    { q: 'Qual empresa criou o iPhone?', options: ['Samsung', 'Google', 'Apple', 'Microsoft'], answer: 2 },
    { q: 'O que significa "CPU"?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Unit'], answer: 0 },
    { q: 'Qual linguagem é mais usada para IA?', options: ['Java', 'C++', 'Python', 'Ruby'], answer: 2 },
    { q: 'O que é "open source"?', options: ['Software pago', 'Código aberto', 'Rede social', 'Sistema operativo'], answer: 1 },
    { q: 'Que protocolo usamos para aceder a websites?', options: ['FTP', 'SMTP', 'HTTP', 'SSH'], answer: 2 },
    { q: 'Qual SO é baseado em Linux?', options: ['Windows', 'macOS', 'Ubuntu', 'MS-DOS'], answer: 2 },
    { q: 'O que é "RAM"?', options: ['Memória permanente', 'Memória de acesso aleatório', 'Rede de área metropolitana', 'Registo automático de memória'], answer: 1 },
    { q: 'Qual formato de imagem suporta transparência?', options: ['JPG', 'BMP', 'PNG', 'TIFF'], answer: 2 },
    { q: 'Quem é considerado o pai da computação?', options: ['Ada Lovelace', 'Alan Turing', 'Charles Babbage', 'John von Neumann'], answer: 1 },
    { q: 'O que faz o "git"?', options: ['Edita imagens', 'Controla versões', 'Compila código', 'Gere bases de dados'], answer: 1 },
    { q: 'Qual é a base do sistema binário?', options: ['8', '10', '16', '2'], answer: 3 },
    { q: 'O que significa "URL"?', options: ['Uniform Resource Locator', 'Universal Reference Link', 'Unified Remote Loader', 'User Resource Locator'], answer: 0 },
    { q: 'Qual empresa desenvolveu o Android?', options: ['Apple', 'Google', 'Microsoft', 'Samsung'], answer: 1 },
    { q: 'O que é "cloud computing"?', options: ['Computação local', 'Computação na nuvem', 'Rede sem fios', 'Inteligência artificial'], answer: 1 },
    { q: 'Que estrutura de dados funciona como FIFO?', options: ['Pilha', 'Fila', 'Árvore', 'Grafo'], answer: 1 },
    { q: 'Quantos bits tem 1 byte?', options: ['4', '8', '16', '32'], answer: 1 },
    { q: 'O que é um "firewall"?', options: ['Antivírus', 'Barreira de rede', 'Tipo de cabo', 'Programa de e-mail'], answer: 1 },
  ]
};
